### ISSUE TITLE
URGENT URGENT: My app have a problem, please fix!

### ISSUE THREAD

**Issue by miguel550** [miguel550/BestOpenSourceProjectEver#4]
Hi guys, my app does not make me feel happy and I'm worried about it. Please, help me make it better.

**Comment by myfirstandoldgithubprofile** [comment]
First, you need to specify what you want. Then, maybe somebody can help you.

**Comment by JoshuaAF** [comment]
If you look at the repo and their previous issue, it's obvious this person is just spamming the hacktoberfest label to be obnoxious

**Comment by RaidAndFade** [comment]
hey bro i got u fam squad just look at that latest PR bro its lit fam 🔥 #5

**Comment by miguel550** [comment]
@RaidAndFade your PR fixed this issue, I'll will now close it.

**Comment by RaidAndFade** [comment]
👍
